AWSTemplateFormatVersion: 2010-09-09
Description: Creates a VPC with public and private subnets , create instance and allow ssh and http
Resources:
  VPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 192.168.101.0/24
      Tags:
        - Key: "VPC-name"
          Value: "VPC02-mariam"
        
  PublicSubnetA: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: "eu-north-1a" 
      CidrBlock: 192.168.101.0/28
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
    
  PrivateSubnetB: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: "eu-north-1b"
      CidrBlock: 192.168.101.32/28
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC

## updates to add instance and allow traffic to it 

# to allow intance to access the internet 
# Internet Gateway allows communication between our VPC and the internet
  InternetGateway:
    Type: AWS::EC2::InternetGateway